### ISSUE TITLE
访问/Login/index.html出现

### ISSUE THREAD

**Issue by biner88** [static7/past#2]
`Argument 1 passed to app\listener\admin\LogRecord::routeAnalyze() must be an instance of app\listener\admin\object or null, instance of think\route\Domain given, called in D:\wwwroot\past\app\listener\admin\LogRecord.php on line 19`

**Comment by static7** [comment]
请问你改动了什么?

**Comment by biner88** [comment]
只是改了配置，没改代码，app\listener\admin\LogRecord.php 19行注释了就正常了，PHP 7.1.15

**Comment by static7** [comment]
配置不要乱改的,如果不了解tp6, 建议不要乱改

**Comment by biner88** [comment]
改了数据库配置，和域名绑定，其他的没动

**Comment by static7** [comment]
.env改动没有?

**Comment by biner88** [comment]
没生成这个文件

**Comment by static7** [comment]
我晕,   .example.env  这个文件重命名.env

**Comment by biner88** [comment]
我试过，搞了还是一样的错误！
还有这里也出错
`[2] ErrorException in UserCenter.php line 69
long2ip() expects parameter 1 to be integer, string given`
我觉得可能是我php版本不兼容吧

**Comment by static7** [comment]
建议你 学习一下强类型入参吧

**Comment by biner88** [comment]
long2ip这个问题可能是不支持IPV6 地址.

**Comment by biner88** [comment]
强类型我会的，我又没改动你的代码，我晕，你老是说我的问题，我是提出一些意见而已。
我就改了下数据库连接方式而已，如果你觉得是我个人问题，那就算了！
